export const ROUTES = {
  PAY: "/test/pay",
  SUBSCRIBE: "/subscriptions/subscribe",
  BILLING_PLANS: "/subscriptions/billing-plans",
  READER_START_REG: "/reader/start-process-register",
  READER_ACTIVATION: "/reader/activateAccount",
  GENRES: "/genre",
  TASK: "/task",
  TASK_FORM_FIELDS: "/task/get-form-fields",
  TASK_SUBMIT_FORM: "/task/submit-form",
  TASK_ID: "/task/get-assignees-task-id",
  TASK_UPLOAD: "/task/uploadFile",
  AUTH_LOGIN: "/auth/login",
  MERCHANT_REGISTER: "/merchant",
  MERCHANT_ALL_ACTIVE: "/merchant/active",
  ORDER: "/order",
  WRITER_START_REG: "/writer/start-process-register",
  WRITER_ACTIVATION: "/writer/activateAccount",
  WRITER_GET_TASK_ID: "/writer/getTaskId",
  LITERARY_WORK_UPLOAD: "/literaryWork/upload",
  GET_MEMBERSHIP_APPLICATIONS: "/boardMember/membershipApplications",
  GET_MEMBERSHIP_APPLICATION: "/boardMember/membershipApplication",
  BOOK_REQUEST_START_PUBLISHING: "/bookRequest/start-process-book-publishing",
  BOOKS: "/book",
  MEMBERSHIP_FEE_PAYMENT: "/writer/membership-fee-payment",
  START_PLAGIARSM_DETECTION: "/book/start-process-plagiarism-detection",
  SUBSCRIPTIONS: "/subscriptions",
};

export const AMOUNT = [
  { value: 1, label: "1" },
  { value: 2, label: "2" },
  { value: 3, label: "3" },
  { value: 4, label: "4" },
  { value: 5, label: "5" },
  { value: 6, label: "6" },
  { value: 7, label: "7" },
  { value: 8, label: "8" },
  { value: 9, label: "9" },
  { value: 10, label: "10" },
  { value: 11, label: "11" },
  { value: 12, label: "11" },
  { value: 13, label: "13" },
  { value: 14, label: "14" },
  { value: 15, label: "15" },
  { value: 16, label: "16" },
  { value: 17, label: "17" },
  { value: 18, label: "18" },
  { value: 19, label: "19" },
  { value: 20, label: "20" },
  { value: 21, label: "21" },
  { value: 22, label: "22" },
  { value: 23, label: "23" },
  { value: 24, label: "24" },
  { value: 25, label: "25" },
];

export const ORDER_STATUS = [
  { value: "INITIATED", label: "INITIATED" },
  { value: "CREATED", label: "CREATED" },
  { value: "COMPLETED", label: "COMPLETED" },
  { value: "CANCELED", label: "CANCELED" },
  { value: "INVALID", label: "INVALID" },
  { value: "EXPIRED", label: "EXPIRED" },
  { value: "ALL", label: "ALL" },
];

export const SUBSCRIPTION_STATUS = [
  { value: "INITIATED", label: "INITIATED" },
  { value: "CREATED", label: "CREATED" },
  { value: "COMPLETED", label: "COMPLETED" },
  { value: "CANCELED", label: "CANCELED" },
  { value: "EXPIRED", label: "EXPIRED" },
  { value: "ALL", label: "ALL" },
];
